import { Capability } from "./types";

export const CAPABILITY_REGISTRY: Record<string, Capability> = {
  "pdf.merge": {
    id: "pdf.merge",
    name: "Merge PDF",
    category: "organize",
    inputFormats: ["pdf"],
    outputFormats: ["pdf"],
    processingMode: "client",
    destructive: false,
    supportsPreview: false,
    supportsBatch: true,
    supportsAI: true,
    summary: "Combine multiple PDFs into one clean final file.",
    acceptsMultiple: true,
    primaryLabel: "Merge Files",
  },
  "pdf.split": {
    id: "pdf.split",
    name: "Split PDF",
    category: "organize",
    inputFormats: ["pdf"],
    outputFormats: ["pdf"],
    processingMode: "client",
    destructive: false,
    supportsPreview: false,
    supportsBatch: false,
    supportsAI: true,
    summary: "Break a PDF into multiple files using page ranges.",
    acceptsMultiple: false,
    primaryLabel: "Split PDF",
  },
  "pdf.extract": {
    id: "pdf.extract",
    name: "Extract Pages",
    category: "organize",
    inputFormats: ["pdf"],
    outputFormats: ["pdf"],
    processingMode: "client",
    destructive: false,
    supportsPreview: false,
    supportsBatch: false,
    supportsAI: true,
    summary: "Pull just the pages you need into a new document.",
    acceptsMultiple: false,
    primaryLabel: "Extract Pages",
  },
  "pdf.delete": {
    id: "pdf.delete",
    name: "Delete Pages",
    category: "organize",
    inputFormats: ["pdf"],
    outputFormats: ["pdf"],
    processingMode: "client",
    destructive: true,
    supportsPreview: false,
    supportsBatch: false,
    supportsAI: true,
    summary: "Remove unwanted pages before you send the file.",
    acceptsMultiple: false,
    primaryLabel: "Delete Pages",
  },
  "pdf.rotate": {
    id: "pdf.rotate",
    name: "Rotate PDF",
    category: "organize",
    inputFormats: ["pdf"],
    outputFormats: ["pdf"],
    processingMode: "client",
    destructive: false,
    supportsPreview: false,
    supportsBatch: false,
    supportsAI: true,
    summary: "Fix upside-down scans with a single action.",
    acceptsMultiple: false,
    primaryLabel: "Rotate Pages",
  },
  "pdf.watermark": {
    id: "pdf.watermark",
    name: "Add Watermark",
    category: "secure",
    inputFormats: ["pdf"],
    outputFormats: ["pdf"],
    processingMode: "client",
    destructive: false,
    supportsPreview: false,
    supportsBatch: false,
    supportsAI: true,
    summary: "Stamp draft, confidential, or brand text across pages.",
    acceptsMultiple: false,
    primaryLabel: "Add Watermark",
  },
  "pdf.page-numbers": {
    id: "pdf.page-numbers",
    name: "Page Numbers",
    category: "organize",
    inputFormats: ["pdf"],
    outputFormats: ["pdf"],
    processingMode: "client",
    destructive: false,
    supportsPreview: false,
    supportsBatch: false,
    supportsAI: true,
    summary: "Insert clean page numbers for submissions and reviews.",
    acceptsMultiple: false,
    primaryLabel: "Add Numbers",
  },
  "pdf.blank": {
    id: "pdf.blank",
    name: "Create Blank PDF",
    category: "create",
    inputFormats: [],
    outputFormats: ["pdf"],
    processingMode: "client",
    destructive: false,
    supportsPreview: false,
    supportsBatch: false,
    supportsAI: true,
    summary: "Start from scratch and place text on a fresh page.",
    acceptsMultiple: false,
    primaryLabel: "Create PDF",
  }
};
