import { Capability } from "./types";

export const CAPABILITY_REGISTRY: Record<string, Capability> = {
  "pdf.merge": {
    id: "pdf.merge",
    name: "Merge PDF",
    category: "organize",
    supportedInputTypes: ["application/pdf"],
    supportedOutputTypes: ["application/pdf"],
    processingEngine: "pdf-lib",
    clientServerSuitability: "isomorphic",
    workerRequirement: "none",
    isDestructive: false,
    supportsPreview: true,
    summary: "Combine multiple PDFs into one clean final file.",
    supportsBatch: true,
  },
  "pdf.split": {
    id: "pdf.split",
    name: "Split PDF",
    category: "organize",
    supportedInputTypes: ["application/pdf"],
    supportedOutputTypes: ["application/pdf"],
    processingEngine: "pdf-lib",
    clientServerSuitability: "isomorphic",
    workerRequirement: "none",
    isDestructive: false,
    supportsPreview: true,
    summary: "Break a PDF into multiple files using page ranges.",
    supportsBatch: false,
  },
  "pdf.extract": {
    id: "pdf.extract",
    name: "Extract Pages",
    category: "organize",
    supportedInputTypes: ["application/pdf"],
    supportedOutputTypes: ["application/pdf"],
    processingEngine: "pdf-lib",
    clientServerSuitability: "isomorphic",
    workerRequirement: "none",
    isDestructive: false,
    supportsPreview: true,
    summary: "Pull just the pages you need into a new document.",
    supportsBatch: false,
  },
  "pdf.delete": {
    id: "pdf.delete",
    name: "Delete Pages",
    category: "organize",
    supportedInputTypes: ["application/pdf"],
    supportedOutputTypes: ["application/pdf"],
    processingEngine: "pdf-lib",
    clientServerSuitability: "isomorphic",
    workerRequirement: "none",
    isDestructive: true,
    supportsPreview: true,
    summary: "Remove unwanted pages before you send the file.",
    supportsBatch: false,
  },
  "pdf.rotate": {
    id: "pdf.rotate",
    name: "Rotate PDF",
    category: "organize",
    supportedInputTypes: ["application/pdf"],
    supportedOutputTypes: ["application/pdf"],
    processingEngine: "pdf-lib",
    clientServerSuitability: "isomorphic",
    workerRequirement: "none",
    isDestructive: false,
    supportsPreview: true,
    summary: "Fix upside-down scans with a single action.",
    supportsBatch: false,
  },
  "pdf.watermark": {
    id: "pdf.watermark",
    name: "Add Watermark",
    category: "secure",
    supportedInputTypes: ["application/pdf"],
    supportedOutputTypes: ["application/pdf"],
    processingEngine: "pdf-lib",
    clientServerSuitability: "isomorphic",
    workerRequirement: "none",
    isDestructive: false,
    supportsPreview: true,
    summary: "Stamp draft, confidential, or brand text across pages.",
    supportsBatch: false,
  },
  "pdf.page-numbers": {
    id: "pdf.page-numbers",
    name: "Page Numbers",
    category: "organize",
    supportedInputTypes: ["application/pdf"],
    supportedOutputTypes: ["application/pdf"],
    processingEngine: "pdf-lib",
    clientServerSuitability: "isomorphic",
    workerRequirement: "none",
    isDestructive: false,
    supportsPreview: true,
    summary: "Add professional page numbering to your document.",
    supportsBatch: false,
  },
  "pdf.blank": {
    id: "pdf.blank",
    name: "Create Blank PDF",
    category: "create",
    supportedInputTypes: [],
    supportedOutputTypes: ["application/pdf"],
    processingEngine: "pdf-lib",
    clientServerSuitability: "isomorphic",
    workerRequirement: "none",
    isDestructive: false,
    supportsPreview: false,
    summary: "Generate a new blank PDF with a custom title and body.",
    supportsBatch: false,
  },
  "pdf.rearrange": {
    id: "pdf.rearrange",
    name: "Rearrange Pages",
    category: "organize",
    supportedInputTypes: ["application/pdf"],
    supportedOutputTypes: ["application/pdf"],
    processingEngine: "pdf-lib",
    clientServerSuitability: "isomorphic",
    workerRequirement: "none",
    isDestructive: false,
    supportsPreview: true,
    summary: "Drag and drop pages into a new order.",
    supportsBatch: false,
  },
  "pdf.redact": {
    id: "pdf.redact",
    name: "Redact PDF",
    category: "secure",
    supportedInputTypes: ["application/pdf"],
    supportedOutputTypes: ["application/pdf"],
    processingEngine: "pdf-lib",
    clientServerSuitability: "isomorphic",
    workerRequirement: "none",
    isDestructive: true,
    supportsPreview: true,
    summary: "Black out sensitive information permanently.",
    supportsBatch: false,
  },
  "pdf.sign": {
    id: "pdf.sign",
    name: "Sign PDF",
    category: "create",
    supportedInputTypes: ["application/pdf"],
    supportedOutputTypes: ["application/pdf"],
    processingEngine: "pdf-lib",
    clientServerSuitability: "isomorphic",
    workerRequirement: "none",
    isDestructive: false,
    supportsPreview: true,
    summary: "Place your signature directly onto the document.",
    supportsBatch: false,
  },
  "pdf.compress": {
    id: "pdf.compress",
    name: "Compress PDF",
    category: "organize",
    supportedInputTypes: ["application/pdf"],
    supportedOutputTypes: ["application/pdf"],
    processingEngine: "pdf-lib",
    clientServerSuitability: "isomorphic",
    workerRequirement: "none",
    isDestructive: false,
    supportsPreview: false,
    summary: "Reduce file size while attempting to preserve quality.",
    supportsBatch: false,
  },
  "pdf.ocr": {
    id: "pdf.ocr",
    name: "OCR PDF",
    category: "understand",
    supportedInputTypes: ["application/pdf"],
    supportedOutputTypes: ["application/pdf"],
    processingEngine: "tesseract-wasm",
    clientServerSuitability: "client-only",
    workerRequirement: "required",
    isDestructive: false,
    supportsPreview: false,
    summary: "Make scanned text searchable and selectable.",
    supportsBatch: false,
  },
  "pdf.pdf-to-image": {
    id: "pdf.pdf-to-image",
    name: "PDF to JPG/PNG",
    category: "convert",
    supportedInputTypes: ["application/pdf"],
    supportedOutputTypes: ["image/jpeg", "image/png"],
    processingEngine: "pdfjs-canvas",
    clientServerSuitability: "client-only",
    workerRequirement: "optional",
    isDestructive: false,
    supportsPreview: false,
    summary: "Convert PDF pages into high-quality images.",
    supportsBatch: false,
    aiActionSchema: {
      type: "object",
      properties: { format: { type: "string", enum: ["jpeg", "png"] }, scale: { type: "number" } },
    }
  },
  "pdf.extract-text": {
    id: "pdf.extract-text",
    name: "Extract Text",
    category: "understand",
    supportedInputTypes: ["application/pdf"],
    supportedOutputTypes: ["application/json"],
    processingEngine: "pdfjs",
    clientServerSuitability: "isomorphic",
    workerRequirement: "optional",
    isDestructive: false,
    supportsPreview: false,
    summary: "Extract all text from a PDF with bounding boxes and page associations.",
    supportsBatch: false,
    aiActionSchema: {
      type: "object",
      properties: {},
    }
  },
  "pdf.analyze-structure": {
    id: "pdf.analyze-structure",
    name: "Analyze Structure",
    category: "understand",
    supportedInputTypes: ["application/pdf"],
    supportedOutputTypes: ["application/json"],
    processingEngine: "pdfjs-heuristics",
    clientServerSuitability: "isomorphic",
    workerRequirement: "optional",
    isDestructive: false,
    supportsPreview: false,
    summary: "Identify headings, text blocks, and document metadata.",
    supportsBatch: false,
    aiActionSchema: {
      type: "object",
      properties: {},
    }
  },
  "pdf.pdf-to-word": {
    id: "pdf.pdf-to-word",
    name: "PDF to Word",
    category: "convert",
    supportedInputTypes: ["application/pdf"],
    supportedOutputTypes: ["application/vnd.openxmlformats-officedocument.wordprocessingml.document"],
    processingEngine: "cloud-document-services",
    clientServerSuitability: "server-only",
    workerRequirement: "none",
    isDestructive: false,
    supportsPreview: false,
    summary: "Convert PDF to editable Word document (Requires Backend).",
    supportsBatch: false,
    aiActionSchema: {
      type: "object",
      properties: {},
    }
  },
  "pdf.pdf-to-excel": {
    id: "pdf.pdf-to-excel",
    name: "PDF to Excel",
    category: "convert",
    supportedInputTypes: ["application/pdf"],
    supportedOutputTypes: ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"],
    processingEngine: "cloud-document-services",
    clientServerSuitability: "server-only",
    workerRequirement: "none",
    isDestructive: false,
    supportsPreview: false,
    summary: "Convert PDF to Excel spreadsheet (Requires Backend).",
    supportsBatch: false,
    aiActionSchema: {
      type: "object",
      properties: {},
    }
  },
  "pdf.extract-tables": {
    id: "pdf.extract-tables",
    name: "Extract Tables",
    category: "understand",
    supportedInputTypes: ["application/pdf"],
    supportedOutputTypes: ["application/json", "text/csv"],
    processingEngine: "pdfjs-heuristics",
    clientServerSuitability: "isomorphic",
    workerRequirement: "optional",
    isDestructive: false,
    supportsPreview: false,
    summary: "Detect and extract tables into structured data.",
    supportsBatch: false,
    aiActionSchema: {
      type: "object",
      properties: {},
    }
  },
};
